### ISSUE TITLE
Question: Live reloading "mobile" after making changes on "core"

### ISSUE THREAD

**Issue by stupidSheep** [benorama/ngrx-demo-apps#10]
Hi @benorama 

First and foremost, thank you for putting this example up on GitHub :-)
Is it possible to enable live reloading when making changes to "core" on "mobile"?

If I make changes to "core" (with 'tsc -w' running), then "web" is automatically reloaded with the updated "core" module ("web" was started with "ng serve").

Yet the same does not happen if I run "mobile" with "ionic serve" - changes in "core" won't be reflected in the ionic app (hot reloading for code within the "mobile" folder works though)

Do you know if it's possible to live reload "mobile" too if "core" changes?
I'm afraid I'm a complete beginner with frontend technologies and overwhelmed by the amount of tools and configuration involved, so I don't even know where to start looking for information.

**Comment by benorama** [comment]
Indeed, it's possible that changes are not detected by Ionic.
We are currently focusing on the web version to stabilize the core.
I'll let you know if we find a solution for that when we'll be back on the mobile version.

Welcome to the wonderful world of frontend technologies.... :)

**Comment by benorama** [comment]
@stupidSheep Here is the new solution (much more elegant) for Angular5 and Ionic3 ! It supports live reloading for Ionic. https://medium.com/@benorama/sharing-ngrx-based-logic-between-angular5-web-app-and-ionic3-mobile-app-77c19470cccc
