### ISSUE TITLE
update the link parts for angular-cli and update to ngrx v4

### ISSUE THREAD

**Issue by axtho** [benorama/ngrx-demo-apps#13]
... starting with angular-cli@1.3.0 the way to link libraries has somewhat progressed. 
Also, NGRX has moved on quite a bit with v4 being out of beta.

I think an update to this repo would be helpful.

I have been working with this modified setup with NG 4.3+ and NGRX 4+ until the CLI 1.3.0 broke the way linking works. Currently I do not have the time to figure that one out right now, otherwise I could add a PR here.

Here is [a story from the cli](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/linked-library.md).

There is also an [open PR at angular](https://github.com/angular/angular/pull/16486) about a guide to include libraries properly.

... the pain of living at the frontier ...

**Comment by benorama** [comment]
Yes, we have also tried to upgrade to latest lib and faced some issue...
Work in progress!

**Comment by axtho** [comment]
Any news on progress?

**Comment by benorama** [comment]
@axtho Here is the new solution (much more elegant) for Angular5 and Ionic3 ! https://medium.com/@benorama/sharing-ngrx-based-logic-between-angular5-web-app-and-ionic3-mobile-app-77c19470cccc

**Comment by axtho** [comment]
@benorama thanks. I was looking at the Nx solution as well, just wanted to wait until it is stable enough (and they sorted a way out to hold your ngrx files in submodules).
