### ISSUE TITLE
Error in Angular 2 final

### ISSUE THREAD

**Issue by adamwuyu** [benorama/ngrx-demo-apps#2]
Hi, I have the latest Angular CLI, and I tried this repo step by step, until "ng serve":
![image](https://cloud.githubusercontent.com/assets/2903328/18622376/dda9f458-7e60-11e6-84c3-088ed8f663bd.png)

Then I tried to follow the migration instruction here: https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14

After that I still get following errors:
![image](https://cloud.githubusercontent.com/assets/2903328/18622390/1c1ea4b8-7e61-11e6-8d4a-2945b5c7f1ea.png)

I guess you have  much better knowledge on how to fix this. THX!

**Comment by benorama** [comment]
Hi, I'm still waiting for Ionic2 to be upgraded (to beta12).
In beta11, we are currently stuck with angular rc4 in Ionic beta 11 (https://github.com/driftyco/ionic2-app-base/blob/master/package.json)

**Comment by benorama** [comment]
I finally managed to upgraded to Angular final (2.0.2) and Ionic2 rc.0!
Except works fine, except for `nom link`, when you try to use effects... 
So if someone finds a workaround for `nom link`, let know.
