### ISSUE TITLE
Example for new versions?

### ISSUE THREAD

**Issue by axtho** [benorama/ngrx-demo-apps#8]
I really like this example and I am setting up a [system](https://github.com/digitaldeacon/memberhive2) similar to this.

Angular, Angular-Cli and Typescript have changed somewhat since your example setup. I am trying to use the latest stuff (including ngrx/platform) but getting issues (either compiling or installing or importing the core).

Simply ngc with your tsconfig gives compiler error

I have used yarn link, but there are issue with the typing files (js in ts not allowed).

This is the config that got me relatively close to working:
```
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "outDir": "./dist",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "paths": {
      "@ngrx/platform": ["./node_modules/@ngrx/platform"]
    }
  },
  "exclude": [
    "node_modules",
    "dist",
    "scripts"
  ],
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit" : true
  }
}
```

Do you have a working example for all the latest dependencies?

**Comment by benorama** [comment]
Indeed, I've to upgrade the libs.
I'll try to do that this WE.

**Comment by axtho** [comment]
I have updated our project with the latest meanderings ... it is still a mess (web compiles when I leave out the core module). Maybe it will help with some things (e.g. how not to do it 💃 ).

There is also an interesting issue about AoT compilation of yarn/ npm link'ed custom modules [over here](https://github.com/angular/angular-cli/issues/3854).

Looking forward to see how you get this going ;)

**Comment by benorama** [comment]
Hi, I've upgraded all the libs, especially `angular 4.0.1` for *core+web* and `angular 2.4.8` for *mobile*.
I was able to run both *mobile* and *web* locally.
Let me know how it goes on your side.

**Comment by axtho** [comment]
Hi Benoit. Thanks for the upgrade. It looks good so far. There is an issue with the mobile but that may be my env (see error below). 

I wonder, did you try to link the packages as well? It works for me when I `yarn link` the core to web and then remove the node_modules/ folder. After that ng serve works beautifully. It is the issue as described in the link I posted earlier.

Error for `ionic serve`:

```
Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/hacktisch/ang2/ngrx-demo-apps/mobile/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by benorama** [comment]
Indeed, I've got the same `reflect-metadata` issue on the mobile version.
I don't know why I was able to run it yesterday...
I tried the following with no luck:
- upgrade to angular 4.0.1,
- upgrade to Ionic CLI v3 beta,
- upgrade to Ionic v3 beta.

Since angular 4 is not yet officially supported, we might have to wait a little bit.

**Comment by axtho** [comment]
Seems to be a node issue: https://github.com/driftyco/ionic-cli/issues/1913 (I am running 7.7). I will try to solve that tomorrow. And also look into the yarn/npm link issue. There must be a way to get that going.

**Comment by axtho** [comment]
Adding this to the tsconfig for web does the link trick:

```
"paths": {
      "@angular/common": ["../node_modules/@angular/common"],
      "@angular/compiler": ["../node_modules/@angular/compiler"],
      "@angular/compiler-cli": ["../node_modules/@angular/compiler-cli"],
      "@angular/core": ["../node_modules/@angular/core"],
      "@angular/platform-browser": ["../node_modules/@angular/platform-browser"],
      "@ngrx/core": ["../node_modules/@ngrx/core"],
      "@ngrx/effects": ["../node_modules/@ngrx/effects"],
      "@ngrx/store": ["../node_modules/@ngrx/store"],
      "@types/node": ["../node_modules/@types/node"],
      "rxjs": ["../node_modules/rxjs"],
      "tslint": ["../node_modules/tslint"],
      "zone.js": ["../node_moduleszone.js"]
    }
```

I.E. all deps that the core requires need to be in the paths section for the tsconfig file that will include the core. I guess the same will be true for the mobile part.

**Comment by benorama** [comment]
@axtho You might want to give a try. @lbertenasco did some fixes.
Both web and mobile are now working again on my machine (with `yarn link`).
Let us know!
